REM //////////////////////////////////////////
REM // COMMON AUTOMATIC COPY : MXIMCryptoki //
REM //////////////////////////////////////////

attrib -r D:\projects\HSM\delivery\vc\include\MXIMConvert.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMCryptoki.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMCryptokiDefs.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMCryptokiError.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMCryptokiInfo.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMCryptokiObject.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMCryptokiObjectAttribute.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMCryptokiObjectAttributes.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMCryptokiObjects.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMData.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMECPrivateKey.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMECPublicKey.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMKey.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMMechanism.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMMechanismInfo.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMMechanisms.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMPrivateKey.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMPublicKey.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMRSAPrivateKey.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMRSAPublicKey.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMSession.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMSessionInfo.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMSessions.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMSlot.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMSlotInfo.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMSlots.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMSTLConvert.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMSTLString.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMStorage.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMToken.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMTokenInfo.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMTokens.h
attrib -r D:\projects\HSM\delivery\vc\include\MXIMTrace.h

copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMConvert.h						D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMCryptoki.h						D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMCryptokiDefs.h					D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMCryptokiError.h                D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMCryptokiInfo.h                 D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMCryptokiObject.h               D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMCryptokiObjectAttribute.h		D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMCryptokiObjectAttributes.h       D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMCryptokiObjects.h              D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMData.h                         D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMECPrivateKey.h                 D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMECPublicKey.h                  D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMKey.h							D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMMechanism.h                    D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMMechanismInfo.h                D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMMechanisms.h                   D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMPrivateKey.h                   D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMPublicKey.h                    D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMRSAPrivateKey.h                D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMRSAPublicKey.h                 D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMSession.h                      D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMSessionInfo.h                  D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMSessions.h                     D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMSlot.h                         D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMSlotInfo.h					  D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMSlots.h                        D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMSTLConvert.h                   D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMSTLString.h                    D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMStorage.h                      D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMToken.h                        D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMTokenInfo.h                    D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMTokens.h                       D:\projects\HSM\delivery\vc\include
copy D:\projects\HSM\hsm_core\MXIMCryptoki\include\MXIMTrace.h                        D:\projects\HSM\delivery\vc\include
                                                                            
                                                                            
attrib +r D:\projects\HSM\delivery\vc\include\MXIMConvert.h                 
attrib +r D:\projects\HSM\delivery\vc\include\MXIMCryptoki.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMCryptokiDefs.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMCryptokiError.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMCryptokiInfo.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMCryptokiObject.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMCryptokiObjectAttribute.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMCryptokiObjectAttributes.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMCryptokiObjects.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMData.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMECPrivateKey.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMECPublicKey.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMKey.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMMechanism.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMMechanismInfo.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMMechanisms.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMPrivateKey.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMPublicKey.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMRSAPrivateKey.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMRSAPublicKey.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMSession.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMSessionInfo.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMSessions.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMSlot.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMSlotInfo.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMSlots.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMSTLConvert.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMSTLString.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMStorage.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMToken.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMTokenInfo.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMTokens.h
attrib +r D:\projects\HSM\delivery\vc\include\MXIMTrace.h

